weight: "/yolov5n.pt"
# weight:  "/home/ccy/planr_ws/src/yolo_people/yolo_people/weights/yolov5s.pt"
input_size: 640
class_num: 30
class_name: ["face"]
threshold:
  iou: 0.45
  confidence: 0.6
device: "0"
